version: '3'
services:
  mysql:
    container_name: mallMysql
    image: mysql:5.7
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
    env_file:
      - docker.env
    network_mode: 'bridge'
